import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { applyStylePatch, resolveCaptionStyle } from '../src/lib/style-resolver.ts';
import { migrateLegacyTranslationTransforms, resolveCaptionPairs, setTranslationCueStyle, setTranslationTrackStyle } from '../src/lib/caption-tracks.ts';
import { captionTransform, hasCaptionTransform } from '../src/lib/caption-transform.ts';
import { decodeVersionTwoProject, serializeProjectSnapshot } from '../src/lib/project-schema.ts';
import { buildTimelineRenderPlan, serializeStyle } from '../src/lib/export-render-plan.ts';
import { reconcileCaptionScriptDraft, splitCaptionScriptBlock } from '../src/lib/caption-script.ts';
import { replaceVisibleCaptionScript } from '../src/lib/project-editor.ts';

// Frozen output generated by executing origin/main's actual caption resolver
// at the recorded revision, before the track-ownership implementation.
const legacy = JSON.parse(readFileSync(new URL('./fixtures/legacy-caption-layout.json', import.meta.url), 'utf8'));
const fixture = () => structuredClone(legacy.project);
const reopen = (p) => decodeVersionTwoProject(JSON.parse(serializeProjectSnapshot(p)));
const styles = (p, id) => resolveCaptionPairs(p, id).map((pair) => serializeStyle(pair.style, new Map()));
const transforms = (p, id) => resolveCaptionPairs(p, id).map((pair) => captionTransform(pair.style));
const primary = (p) => p.captions.map((cue) => captionTransform(resolveCaptionStyle(p.projectStyle, cue)));
const target = { position: { x: 0.45, y: 0.3 }, rotation: 25, scale: 1.4, scaleX: 0.8, scaleY: 1.2, box: { width: 0.6, height: 0.2 } };

for (const hidden of [false, true]) test(`partial track transforms use a deterministic visible reference (first hidden: ${hidden})`, () => {
  const p = fixture();
  p.captions[0].timelineVisible = !hidden;
  for (const track of p.captionTracks.translations) track.cues[0].timelineVisible = !hidden;
  const reversed = structuredClone(p);
  reversed.captions.reverse();
  for (const track of reversed.captionTracks.translations) track.cues.reverse();
  const reference = hidden ? 1 : 0;
  const expectedTranslation = { ...transforms(p, 'fr')[reference], rotation: 71 };
  const expectedPrimary = { ...primary(p)[reference], rotation: 71 };
  for (const project of [p, reversed]) {
    const translated = reopen(setTranslationTrackStyle(project, 'fr', { rotation: 71 }));
    assert.deepEqual(transforms(translated, 'fr'), [expectedTranslation, expectedTranslation]);
    assert.deepEqual(styles(translated, 'de'), styles(project, 'de'));
    assert.deepEqual(primary(translated), primary(project));
    const next = reopen(applyStylePatch(project, undefined, 'all', { rotation: 71 }));
    assert.deepEqual(primary(next), [expectedPrimary, expectedPrimary]);
  }
});

test('migration reference ties use cue IDs and empty legacy tracks migrate without inventing cues', () => {
  const p = fixture();
  for (const track of p.captionTracks.translations) {
    for (const cue of track.cues) { cue.startMs = 0; cue.endMs = 1000; cue.timelineVisible = false; }
  }
  const expected = transforms(p, 'fr')[0];
  p.captions.reverse();
  assert.deepEqual(transforms(migrateLegacyTranslationTransforms(p), 'fr'), [expected, expected]);
  p.captions = [];
  for (const track of p.captionTracks.translations) track.cues = [];
  const next = reopen(applyStylePatch(p, undefined, 'all', target));
  assert.equal(next.captions.length, 0);
  for (const track of next.captionTracks.translations) {
    assert.ok(track.layoutAnchor);
    assert.deepEqual(track.cues, []);
  }
});

test('appearance-only edits and script saves never migrate legacy translation geometry', () => {
  const p = fixture();
  let next = applyStylePatch(p, 'c0', 'caption', { italic: false });
  next = setTranslationTrackStyle(next, 'fr', { textColor: '#123456' });
  next = reopen(replaceVisibleCaptionScript(next, next.captions.map((cue) => ({ ...cue, text: cue.text + ' edited' }))));
  for (const track of next.captionTracks.translations) {
    assert.equal(Object.hasOwn(track, 'layoutAnchor'), false);
    assert.deepEqual(transforms(next, track.id), transforms(p, track.id));
  }
});

test('invalid recovered timings fail atomically without changing project geometry or content', () => {
  const p = applyStylePatch(fixture(), 'c0', 'caption', target);
  for (const value of [NaN, Infinity, -Infinity]) {
    const draft = structuredClone(p.captions);
    draft[0].startMs = value;
    assert.equal(replaceVisibleCaptionScript(p, draft), p);
  }
});

test('legacy decode/reopen matches origin/main resolver bytes without anchoring or changing preview/export', () => {
  const before = fixture();
  const plan = JSON.stringify(buildTimelineRenderPlan(before).captions);
  let current = before;
  for (let pass = 0; pass < 3; pass++) {
    current = reopen(current);
    for (const track of current.captionTracks.translations) {
      assert.equal(Object.hasOwn(track, 'layoutAnchor'), false);
      assert.equal(JSON.stringify(styles(current, track.id)), JSON.stringify(legacy.styles[track.id]));
      assert.equal(JSON.stringify(styles(before, track.id)), JSON.stringify(legacy.styles[track.id]));
    }
    assert.equal(JSON.stringify(buildTimelineRenderPlan(current).captions), plan);
    assert.deepEqual(primary(current), primary(before));
  }
});

test('first primary transform preserves addressed legacy translation layout and detaches all tracks atomically', () => {
  const before = reopen(fixture());
  const selected = 'c1';
  const next = applyStylePatch(before, selected, 'caption', target);
  assert.deepEqual(primary(next), [target, target]);
  for (const track of before.captionTracks.translations) {
    const expected = transforms(before, track.id)[1];
    assert.deepEqual(transforms(next, track.id), [expected, expected]);
    assert.ok(next.captionTracks.translations.find((t) => t.id === track.id).layoutAnchor);
  }
  const second = applyStylePatch(next, 'c0', 'caption', { position: { y: 0.8 }, scale: 2 });
  for (const track of next.captionTracks.translations) assert.deepEqual(transforms(second, track.id), transforms(next, track.id));
  assert.equal(Object.hasOwn(before.captionTracks.translations[0], 'layoutAnchor'), false);
  assert.deepEqual(primary(reopen(next)), primary(next));
});

test('migration reference without selection is chronological and independent of storage order', () => {
  const p = fixture();
  p.captions.reverse();
  for (const track of p.captionTracks.translations) track.cues.reverse();
  const migrated = migrateLegacyTranslationTransforms(p);
  for (const track of p.captionTracks.translations) {
    const earliest = resolveCaptionPairs(p, track.id).find((pair) => pair.source.id === 'c0');
    for (const value of transforms(migrated, track.id)) assert.deepEqual(value, captionTransform(earliest.style));
  }
});

test('first translation transform only migrates its own track; non-geometry edits never migrate', () => {
  const p = fixture();
  const appearance = setTranslationCueStyle(p, 'fr', 'c1', { textColor: '#FFFFFF' });
  assert.equal(Object.hasOwn(appearance.captionTracks.translations[0], 'layoutAnchor'), false);
  const next = setTranslationCueStyle(p, 'fr', 'c1', target);
  assert.deepEqual(transforms(next, 'fr'), [target, target]);
  assert.deepEqual(styles(next, 'de'), styles(p, 'de'));
  assert.deepEqual(primary(next), primary(p));
  const movedPrimary = applyStylePatch(next, 'c0', 'caption', { position: { y: 0.9 } });
  assert.deepEqual(transforms(movedPrimary, 'fr'), [target, target]);
});

test('primary legacy geometry survives text-only saves and migrates from selected effective geometry on transform', () => {
  const p = fixture();
  const draft = structuredClone(p.captions);
  draft[0].text = 'Edited text';
  const saved = reopen(replaceVisibleCaptionScript(p, draft));
  assert.deepEqual(primary(saved), primary(p));
  const expected = { ...primary(p)[1], position: { ...primary(p)[1].position, y: 0.4 } };
  const transformed = applyStylePatch(saved, 'c1', 'caption', { position: { y: 0.4 } });
  assert.deepEqual(primary(transformed), [expected, expected]);
});

test('split -> transform -> script save -> reopen cannot resurrect stale geometry or lose appearance', () => {
  const p = fixture();
  const split = splitCaptionScriptBlock(p.captions, 'c0', 6, [], 'split-new');
  assert.ok(split);
  const newCue = split.captions.find((cue) => cue.id === 'split-new');
  assert.equal(hasCaptionTransform(newCue.styleOverride), false);
  assert.equal(newCue.styleOverride.italic, true);
  const transformed = applyStylePatch(p, 'c1', 'caption', target);
  const preview = reconcileCaptionScriptDraft(transformed, split.captions);
  for (const cue of preview) assert.deepEqual(captionTransform(resolveCaptionStyle(transformed.projectStyle, cue)), target);
  const saved = reopen(replaceVisibleCaptionScript(transformed, split.captions));
  assert.equal(saved.captions.length, 3);
  for (const cue of saved.captions) {
    assert.deepEqual(captionTransform(resolveCaptionStyle(saved.projectStyle, cue)), target);
    assert.equal(cue.styleOverride.italic, true);
    assert.equal(hasCaptionTransform(cue.styleOverride), false);
  }
  assert.deepEqual(saved.captions.map((cue) => [cue.id, cue.text, cue.startMs, cue.endMs, cue.wordIds]),
    split.captions.map((cue) => [cue.id, cue.text, cue.startMs, cue.endMs, cue.wordIds]));
});

test('cancel/recovered stale drafts never mutate current geometry and save preserves current cue appearance', () => {
  const p = fixture();
  const recovered = JSON.parse(JSON.stringify(p.captions));
  const transformed = applyStylePatch(p, 'c0', 'caption', target);
  transformed.captions[0].styleOverride = { italic: false, textColor: '#FFFFFF' };
  const before = serializeProjectSnapshot(transformed);
  reconcileCaptionScriptDraft(transformed, recovered); // preview or cancel
  assert.equal(serializeProjectSnapshot(transformed), before);
  recovered[0].text = 'Recovered text';
  const saved = reopen(replaceVisibleCaptionScript(transformed, recovered));
  assert.deepEqual(primary(saved), [target, target]);
  assert.equal(saved.captions[0].text, 'Recovered text');
  assert.deepEqual(saved.captions[0].styleOverride, transformed.captions[0].styleOverride);
});
